###
POST http://localhost:3000/expense
Content-Type: application/json

{
    "userId": 2,
    "groupId": 2,
    "description": "poole cafe",
    "cost": 6700000
}

###
GET http://localhost:3000/users/1/groups/2/expenses/made

###
GET http://localhost:3000


###
# POST http://localhost:3000/login
# Content-Type: application/json

# {
#     "username": "admin",
#     "password": "admin"
# }